### ISSUE TITLE
Command Arguments breaks YAML syntax parsing

### ISSUE THREAD

**Issue by wsidl** [JM1/ansible-collection-jm1-libvirt#1]
When creating a domain using `jm1.libvirt.domain`, the hardware arguments must be a dict of (str, str) values. In some cases, the value side of the dict requires multiple parameters for that argument:

```bash
--network network=default,mac=52:54:00:aa:bb:cc,model=virtio
```

Adding these types of arguments to the yaml playbook using this module raises an error saying the value for this argument is in Key=Value Shorthand and not YAML:

```
ERROR! no module/action detected in task.

The error appears to be in '/my/playbook.yml': line 113, column 30, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

          - network: "network=os_net,mac=52:54:00:aa:bb:cc,model=virtio"
                             ^ here

There appears to be both 'k=v' shorthand syntax and YAML in this task. Only one syntax may be used.
```

Python 3.9.7
Ansible Core 2.11.5

**Comment by wsidl** [comment]
Potential solution would be to breakdown the `module_utils/libvirt.py:to_cli_args` function to further test if the value is a dict-type and parse them into a string suitable for the cli:

```yaml
- network:
  - network: "default"
  - mac: "54:52:00:aa:bb:cc"
  - model: "virtio"
```

The function would test for the value type and join them into the appropriate string:

```python
values = value
if isinstance(value, list):
  values = []
  for _value in value:
    if isinstance(_value, dict):
      values.append(",".join([f"{_k}={_v}" for _k, _v in _value]))
    else:
      values.append(str(_value))
  values = ",".join(values)
cli_args += ['--%s' % key.replace('_', '-'), values]
```

This is untested, but should provide the idea

**Comment by wsidl** [comment]
Issue was an incomplete statement after this section. No longer needed.

Weird error response!!

**Comment by JM1** [comment]
Nice to hear that you found my collection :smile:

**Comment by wsidl** [comment]
I have to say good job on it, it's so far the only collection that does what I want it to do (similar to one for Terraform). A couple of "nice to haves" can be provided if you're interested.
