### ISSUE TITLE
why is distribution id used to select which software is required for the host?

### ISSUE THREAD

**Issue by ji-podhead** [JM1/ansible-collection-jm1-libvirt#6]
hi, so i want to deploy debian via libvirt on a rhel9 host.
i noticed that, if you dont specify the image uri, the host os gets selected as the targot os (vm distribution).
ill try if that works and if  i can get a workaround, but cant we introduce a "host-os" variable for the required software?

Thanks und grüße aus berlin:
ji

**Comment by ji-podhead** [comment]
ahh i can just overwrite the variable in the jm1.libvirt.server role, but still confusing

**Comment by JM1** [comment]
You can either specify `image_uri` directly or define `distribution_id` to be something matching an entry in the predefined `image_uri` dictionary. In both cases, you would define those variables for the host that represents your VM in your Ansible inventory. For example, have a look at Ansible collection [jm1.cloudy](https://github.com/JM1/ansible-collection-jm1-cloudy), in particular its inventory, e.g. the [host vars for a Debian 12 (Bookworm)](https://github.com/JM1/ansible-collection-jm1-cloudy/blob/master/inventory/host_vars/lvrt-lcl-session-srv-022-debian12.yml).

The rationale for this style is discussed here: https://gist.github.com/JM1/9363beeb9fb5055e054b5f64aea0a598

**Comment by ji-podhead** [comment]
ah ok, but i needed to create a kvm_host_os field anyway though, because the [rhel cloud-localds issue ](https://github.com/JM1/ansible-collection-jm1-libvirt/pull/7)

**Comment by ji-podhead** [comment]
> ..For example, have a look at Ansible collection [jm1.cloudy](https://github.com/JM1/ansible-collection-jm1-cloudy)...
   - boor da hast du ja noch ne repo die damit zutun hat...  i did not notice that.... 🌪
